"""FIX: Card number column increased to accomodate the long credit card  hash.

Revision ID: 213ffefc00b7
Revises: 04ed894b3520
Create Date: 2023-08-04 19:19:30.803992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213ffefc00b7'
down_revision = '04ed894b3520'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('credit_cards', 'card_number',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
