"""FIX: Card number column.

Revision ID: 8bde2485fbc0
Revises: 213ffefc00b7
Create Date: 2023-08-04 19:45:05.240110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bde2485fbc0'
down_revision = '213ffefc00b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'card_number ',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
     # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_cards', 'card_number ',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###