"""Sebastian changes from main

Revision ID: ba3f5b3e7b46
Revises: dd15135da4c8
Create Date: 2023-08-01 14:33:58.878751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3f5b3e7b46'
down_revision = 'dd15135da4c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('cvv', sa.String(length=10), nullable=False))
    op.add_column('credit_cards', sa.Column('expiry_date', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    op.drop_column('credit_cards', 'expiry_date')
    op.drop_column('credit_cards', 'cvv')
    # ### end Alembic commands ###
