"""Edit user column length from 500 to 255.

Revision ID: d18fe8a861f3
Revises: 6cdcbea9b11d
Create Date: 2023-08-01 16:13:53.022675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18fe8a861f3'
down_revision = '6cdcbea9b11d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
