"""Homelab migration

Revision ID: dd15135da4c8
Revises: c15947d2b7e8
Create Date: 2023-07-31 21:20:47.206248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd15135da4c8'
down_revision = 'c15947d2b7e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
